### ISSUE TITLE
Feature request adding TODO items for later

### ISSUE THREAD

**Issue by keller00** [viseshrp/workedon#43]
I would love to be able to add reminders to be completed later. That being later today, or tomorrow. I think a rolling list of TODOs would be fine, but optionally having the capability of assigning them to e.g.: tomorrow could be useful too.

Let me maybe give an example, I start my workday by checking emails `$workedon catching up on emails`, then I see a new code review from co-worker `$workedon later complete PR #2` to note this. Once I'm done with the emails I check my TODO list with something like `$workedon what`, or TODOs could live in their own spot with `$workedon later what`. I see the list and instead of typing out the whole ticket again I'm thinking there would be some shortcut to transition a TODO to a working on, like `$workedon later 1` (assuming they were numbered).

Thanks for the consideration and the project!

**Comment by viseshrp** [comment]
@keller00 Appreciate the feedback! Thanks. Do you think you could achieve this using tags?
`$ workedon complete PR #2 --tag later` and then to find it:
`$ workedon what --tag later`
Then maybe then edit it to remove the tag after you've completed?
(Both tagging and editing are features being worked on, so the above will not work right now in the current release)

**Comment by keller00** [comment]
Yes, I think that would work.

The one part I’m unclear on is whether doing `$ workedon complete PR #2 --tag later` would end what I’m currently working on, in my example that was working on my emails.

**Comment by viseshrp** [comment]
Ok, I believe that part may have to be done manually by editing a log and removing the tag that you're using to tell if something is incomplete (In this case a tag named "later") once you've completed it. 
Sorry, but this tool is not meant to be a TO-DO list but more so to record what you've done before. I'm hesitant about the `complete` command for that reason. Hope that makes sense 😊
